//
//  ListOrdersInteractor.swift
//  CleanStore
//
//  Created by 도미닉 on 6/11/25.
//  Copyright (c) 2025 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListOrdersBusinessLogic {
    func fetchOrders(request: ListOrders.FetchOrders.Request)
}

protocol ListOrdersDataStore {
    //var name: String { get set }
}

class ListOrdersInteractor: ListOrdersBusinessLogic, ListOrdersDataStore {
    var presenter: ListOrdersPresentationLogic?
    var worker = OrdersWorker(ordersStore: OrdersMemStore())
    //var name: String = ""
    
    // MARK: Fetch Orders
    
    func fetchOrders(request: ListOrders.FetchOrders.Request) {
        worker.fetchOrders { orders in
            let response = ListOrders.FetchOrders.Response()
            self.presenter?.presentOrders(response: response)
        }
    }
}
