//
//  ListOrdersModels.swift
//  CleanStore
//
//  Created by 도미닉 on 6/11/25.
//  Copyright (c) 2025 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListOrders
{
  // MARK: Use cases
  
  enum FetchOrders {
    struct Request {
    }
    struct Response {
    }
    struct ViewModel {
    }
  }
}
