//
//  ListOrdersPresenter.swift
//  CleanStore
//
//  Created by 도미닉 on 6/11/25.
//  Copyright (c) 2025 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListOrdersPresentationLogic {
    func presentOrders(response: ListOrders.FetchOrders.Response)
}

class ListOrdersPresenter: ListOrdersPresentationLogic {
    weak var viewController: ListOrdersDisplayLogic?
    
    // MARK: Fetch Orders
    
    func presentOrders(response: ListOrders.FetchOrders.Response)
    {
        let displayOrders = response.orders.map({ order in
            ListOrders.FetchOrders.ViewModel.DisplayedOrder(id: order.id!, date: order.date.description, email: order.email, name: order.lastName + order.firstName, total: order.total.stringValue)
        })
        let viewModel = ListOrders.FetchOrders.ViewModel(displayedOrders: displayOrders)
        viewController?.displayOrders(viewModel: viewModel)
    }
}
