//
//  ListOrdersPresenter.swift
//  CleanStore
//
//  Created by 도미닉 on 6/11/25.
//  Copyright (c) 2025 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListOrdersPresentationLogic {
    func presentOrders(response: ListOrders.FetchOrders.Response)
}

class ListOrdersPresenter: ListOrdersPresentationLogic {
    weak var viewController: ListOrdersDisplayLogic?
    
    let dateFormatter: DateFormatter = {
      let dateFormatter = DateFormatter()
      dateFormatter.dateStyle = .short
      dateFormatter.timeStyle = .none
      return dateFormatter
    }()
    
    let currencyFormatter: NumberFormatter = {
      let currencyFormatter = NumberFormatter()
      currencyFormatter.numberStyle = .currency
      return currencyFormatter
    }()
    
    // MARK: Fetch Orders
    
    func presentOrders(response: ListOrders.FetchOrders.Response)
    {
        let displayOrders = response.orders.map({ order in
            let date = dateFormatter.string(from: order.date)
            let total = currencyFormatter.string(from: order.total)
            return ListOrders.FetchOrders.ViewModel.DisplayedOrder(id: order.id!, date: date, email: order.email, name: order.firstName + order.lastName, total: total!)
        })
        let viewModel = ListOrders.FetchOrders.ViewModel(displayedOrders: displayOrders)
        viewController?.displayOrders(viewModel: viewModel)
    }
}
