//
//  CreateOrderInteractor.swift
//  CleanStore
//
//  Created by 도미닉 on 6/12/25.
//  Copyright (c) 2025 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateOrderBusinessLogic
{
    var shippingMethods: [String] { get }
    func showOrderToEdit(request: CreateOrder.EditOrder.Request)
    func formatExpirationDate(request: CreateOrder.FormatExpirationDate.Request)
    func createOrder(request: CreateOrder.CreateOrder.Request)
}

protocol CreateOrderDataStore
{
    //var name: String { get set }
    var orderToEdit: Order? { get set }
}

class CreateOrderInteractor: CreateOrderBusinessLogic, CreateOrderDataStore
{
    var presenter: CreateOrderPresentationLogic?
    var worker = OrdersWorker(ordersStore: OrdersMemStore())
    var orderToEdit: Order?
    
    var shippingMethods = [
        ShipmentMethod(speed: .Standard).toString(),
        ShipmentMethod(speed: .OneDay).toString(),
        ShipmentMethod(speed: .TwoDay).toString()
    ]
    
    // MARK: Do something
    
    func showOrderToEdit(request: CreateOrder.EditOrder.Request)
    {
        if let orderToEdit = orderToEdit {
          let response = CreateOrder.EditOrder.Response(order: orderToEdit)
          presenter?.presentOrderToEdit(response: response)
        }
    }
    
    func formatExpirationDate(request: CreateOrder.FormatExpirationDate.Request)
    {
        let response = CreateOrder.FormatExpirationDate.Response(date: request.date)
        presenter?.presentExpirationDate(response: response)
    }
    
    func createOrder(request: CreateOrder.CreateOrder.Request) {
        let orderFormFields = request.orderFormFields
        worker.createOrder(orderToCreate: Order(firstName: orderFormFields.firstName, lastName: orderFormFields.lastName, phone: orderFormFields.phone, email: orderFormFields.email, billingAddress: Address(street1: orderFormFields.billingAddressStreet1, street2: orderFormFields.billingAddressStreet2, city: orderFormFields.billingAddressCity, state: orderFormFields.billingAddressState, zip: orderFormFields.billingAddressZIP), paymentMethod: PaymentMethod(creditCardNumber: orderFormFields.paymentMethodCreditCardNumber, expirationDate: orderFormFields.paymentMethodExpirationDate, cvv: orderFormFields.paymentMethodCVV), shipmentAddress: Address(street1: orderFormFields.shipmentAddressStreet1, street2: orderFormFields.shipmentAddressStreet2, city: orderFormFields.shipmentAddressCity, state: orderFormFields.shipmentAddressState, zip: orderFormFields.shipmentAddressZIP), shipmentMethod: ShipmentMethod(speed: ShipmentMethod.ShippingSpeed(rawValue: orderFormFields.shipmentMethodSpeed)!), date: orderFormFields.date, total: orderFormFields.total)) { order in
            self.presenter?.presentCreatedOrder(response: .init(order: order))
        }
    }
}
