//
//  ShowOrderPresenter.swift
//  CleanStore
//
//  Created by 도미닉 on 6/14/25.
//  Copyright (c) 2025 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowOrderPresentationLogic
{
    func presentOrder(response: ShowOrder.GetOrder.Response)
}

class ShowOrderPresenter: ShowOrderPresentationLogic
{
    weak var viewController: ShowOrderDisplayLogic?
    
    let dateFormatter: DateFormatter = {
      let dateFormatter = DateFormatter()
      dateFormatter.dateStyle = .short
      dateFormatter.timeStyle = .none
      return dateFormatter
    }()
    
    let currencyFormatter: NumberFormatter = {
      let currencyFormatter = NumberFormatter()
      currencyFormatter.numberStyle = .currency
      return currencyFormatter
    }()
    
    func presentOrder(response: ShowOrder.GetOrder.Response)
    {
        let order = response.order
        let viewModel = ShowOrder.GetOrder.ViewModel(
            id: order?.id,
            date: dateFormatter.string(from: order!.date),
            email: order?.email,
            name: order!.firstName + order!.lastName,
            total: currencyFormatter.string(from: order!.total)
        )
        viewController?.displayOrder(viewModel: viewModel)
    }
}
