//
//  ShowOrderViewController.swift
//  CleanStore
//
//  Created by 도미닉 on 6/14/25.
//  Copyright (c) 2025 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SnapKit

protocol ShowOrderDisplayLogic: class
{
    func displayOrder(viewModel: ShowOrder.GetOrder.ViewModel)
}

class ShowOrderViewController: UIViewController, ShowOrderDisplayLogic
{
    var interactor: ShowOrderBusinessLogic?
    var router: (NSObjectProtocol & ShowOrderRoutingLogic & ShowOrderDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = ShowOrderInteractor()
        let presenter = ShowOrderPresenter()
        let router = ShowOrderRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .white
        makeConstrants()
    }
    
    private func makeConstrants() {
        view.addSubview(orderIDLabel)
        view.addSubview(orderDateLabel)
        view.addSubview(orderEmailLabel)
        view.addSubview(orderNameLabel)
        view.addSubview(orderTotalLabel)
        
        orderIDLabel.snp.makeConstraints { make in
            make.centerX.equalTo(view)
            make.centerY.equalTo(view).offset(-100)
        }
        orderDateLabel.snp.makeConstraints { make in
            make.centerX.equalTo(view)
            make.top.equalTo(orderIDLabel.snp.bottom).offset(10)
        }
        orderEmailLabel.snp.makeConstraints { make in
            make.centerX.equalTo(view)
            make.top.equalTo(orderDateLabel.snp.bottom).offset(10)
        }
        orderNameLabel.snp.makeConstraints { make in
            make.centerX.equalTo(view)
            make.top.equalTo(orderEmailLabel.snp.bottom).offset(10)
        }
        orderTotalLabel.snp.makeConstraints { make in
            make.centerX.equalTo(view)
            make.top.equalTo(orderNameLabel.snp.bottom).offset(10)
        }
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewWillAppear(_ animated: Bool)
    {
      super.viewWillAppear(animated)
      getOrder()
    }
    
    let orderIDLabel = UILabel()
    let orderDateLabel = UILabel()
    let orderEmailLabel = UILabel()
    let orderNameLabel = UILabel()
    let orderTotalLabel = UILabel()
    
    func getOrder()
    {
        let request = ShowOrder.GetOrder.Request()
        interactor?.getOrder(request: request)
    }
    
    func displayOrder(viewModel: ShowOrder.GetOrder.ViewModel) {
        orderIDLabel.text =  viewModel.id
        orderDateLabel.text = viewModel.date
        orderEmailLabel.text = viewModel.email
        orderNameLabel.text = viewModel.name
        orderTotalLabel.text = viewModel.total
    }
}
