//
//  ShowOrderInteractor.swift
//  CleanStore
//
//  Created by 도미닉 on 6/14/25.
//  Copyright (c) 2025 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowOrderBusinessLogic
{
  func doSomething(request: ShowOrder.Something.Request)
}

protocol ShowOrderDataStore
{
    var order: Order! { get set }
}

class ShowOrderInteractor: ShowOrderBusinessLogic, ShowOrderDataStore
{
  var presenter: ShowOrderPresentationLogic?
  var worker: ShowOrderWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ShowOrder.Something.Request)
  {
    worker = ShowOrderWorker()
    worker?.doSomeWork()
    
    let response = ShowOrder.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
